// Generated by configure-admin.sh. Public encrypted token blob.
window.FDH_ADMIN_SECRET = {
  "v": 1,
  "kdf": "PBKDF2-SHA256",
  "cipher": "AES-256-GCM",
  "iterations": 600000,
  "salt": "MFacAX0sxb0syuRMOyhuSw==",
  "iv": "Q2Fr1879PQ4XcvLK",
  "ciphertext": "OWvfnFUijENAchh1pPDBMmnoqg72zNaIkH14t00yIsZb3E6rTVOWwWMNAEqjrAKnp+6ZhVJowzQQeuoAZeeMBfqkSTrAo38qoQW5moDgWrVcLTQFt+NBSsxbKunkcI8gZie9DDFl1h0QPetPew=="
};
