window.FDH_BLOG_POSTS = [
  {
    "id": "welcome-to-the-bbs",
    "title": "BLOG SYSTEM ONLINE",
    "date": "2026-09-14",
    "readTime": "1 MIN READ",
    "tags": [
      "META",
      "BBS"
    ],
    "summary": "The blog exists now. This is where future acts of software misconduct get documented.",
    "body": [
      "The board now has a blog. The two newest entries appear on the main page automatically, while every older transmission stays in the archive.",
      "Future posts can be added by editing one data file. No framework, database, CMS or build pipeline required. That would be suspiciously normal."
    ]
  },
  {
    "id": "typescript-data-storing",
    "title": "Typescript data storing?",
    "date": "2026-09-14",
    "readTime": "4 MIN READ",
    "tags": [
      "Typescript"
    ],
    "summary": "The compiler seems to be useful",
    "body": [
      "TypeScript errors contain data. The compiler prints it back. Therefore the compiler can remember things.",
      "People see an error message and fix it. That's unimaginative.",
      "I'm going to store forum data in it."
    ]
  },
  {
    "id": "typescript-data-storage",
    "title": "Typescript Data storage?",
    "date": "2026-09-14",
    "readTime": "3 MIN READ",
    "tags": [
      "Typescript"
    ],
    "summary": "the compiler seems to work as intended",
    "body": [
      "Pushed data into compiler errors on purpose, looks like this might work to store data on purpose.\nwill investigate further"
    ]
  },
  {
    "id": "turning-typescript-into-storage",
    "title": "Turning typescript into storage",
    "date": "2026-09-14",
    "readTime": "1 MIN READ",
    "tags": [
      "Typescript"
    ],
    "summary": "managed another feat",
    "body": [
      "users become interfaces, passwords literal types, threads namespaces, relationships imports."
    ]
  },
  {
    "id": "tscum-0-2-releasing-in-a-few-hours",
    "title": "TScum 0.2 releasing in a few hours",
    "date": "2026-09-15",
    "readTime": "6 MIN READ",
    "tags": [
      "Typescript"
    ],
    "summary": "Grafix update seems to work?",
    "body": [
      "Yes. SchrödingerDB can absolutely become a real module/library, and that is a fantastic TODO 3.5.",
      "The trick is to separate the cursed storage engine from ERRORUM itself. Right now SchrödingerDB is embedded in the forum architecture. We can extract the actual persistence logic into a clean API while keeping the implementation completely deranged.",
      "So somebody could unironically do:",
      "from schrodb import DB",
      "db = DB(\"./data\")",
      "db.set(\"user:42:name\", \"alice\")\ndb.set(\"user:42:role\", \"admin\")",
      "print(db.get(\"user:42:name\"))\nwhile under the hood their value is reconstructed from something like:",
      "xattr A\n+ symlink target B\n+ inode\n+ mode bits\n+ directory mtime\n+ filesystem identity\nNo canonical copy anywhere.",
      "For a first proper library I'd keep the API boring on purpose:",
      "db.set(key, value)\ndb.get(key)\ndb.delete(key)\ndb.exists(key)\ndb.keys(prefix=None)\ndb.compare_and_set(key, expected, new)\ndb.transaction(...)\nMaybe JSON-ish convenience later:",
      "db.put(\"users/alice\", {\n    \"role\": \"admin\",\n    \"likes\": 37\n})\nThe user-facing interface should be painfully normal. The obscenity belongs inside the engine.",
      "We could offer two modes:",
      "SchroDB portable\n  filesystem metadata + symlinks + xattrs where available\n  sensible fallbacks\n  meant to actually be embedded",
      "SchroDB full-heresy\n  Linux only\n  inode dependence\n  xattrs\n  mode bits\n  mtimes\n  symlinks\n  filesystem identity\n  resolver salt\n  free-space entropy\n  all the original SchrödingerDB nonsense\nAnd I'd specifically make it crash loudly if the representations disagree. That's one of the genuinely interesting properties of the design:",
      "representation A says \"hello\"\nrepresentation B + inode + metadata reconstructs \"hello\"\n        =\nvalid",
      "they disagree\n        =\ndatabase corruption\nSo the redundancy isn't just comedy. It becomes a weird integrity mechanism.",
      "Updated development order\n1. TScum v0.2\nField testing + TScum blog series.",
      "2. NineHells\nBuild the polyglot nightmare.",
      "3. Borum\nBatch sovereignty, ERRORLEVEL IPC, PowerShell socket prosthetic, cmd worker colony, generated disposable PHP.",
      "3.5. SchrödingerDB standalone\nExtract the ERRORUM storage mechanism into an embeddable library people can actually use.",
      "Target:",
      "A normal key/value API backed by an extremely abnormal filesystem database.",
      "Likely first implementation: Python package/module, since the existing ERRORUM machinery is already Python-based and it gives us the easiest route to a genuinely usable library.",
      "Then potentially:",
      "schrodb Python package\nCLI\nsimple HTTP adapter\nPHP bindings\nNode bindings\nThe marketing line practically writes itself:",
      "SchrödingerDB: your data exists only if all the wrong parts of the filesystem agree.",
      "4. Forum Dev From Hell site\nContinue documenting all of the above.",
      "And yes, I would treat 3.5 as a real product/library, not another forum. That makes it much funnier when somebody eventually says:",
      "“We're using SchrödingerDB in production.”",
      "and they're completely serious.",
      "Today 10:18 AM\nJarvis we're at Blog post 3/10 to shill tscum. Where are we at with the frontend for tscum and the todo list?",
      "Jarvis status board online. 🫡",
      "TScum frontend is DONE. v0.2 “Grafix Update” is the browser build. It has the Node HTTP frontend, registration/login, threads, replies, per-post likes via Widen union, search, inbox, rotating admin display, and real tsserver-PID browser sessions. The actual cursed mechanisms underneath are still intact: TypeScript assignability does auth, conditional/template-literal types do search, unions do likes, etc. The final ZIP passed both the normal and browser smoke tests.",
      "So we're not waiting on frontend development anymore. We're in field-test + propaganda phase. 😭",
      "JARVIS // CURRENT TODO\n1. TScum v0.2 field test\nRun Grafix for roughly 4–5 days as an actual forum. Break things, fix anything real users could hit, then freeze the release. TScum v0.2 Grafix",
      "2. TScum shill campaign: 3/10\nWe're currently at blog post 3 of 10. Continue the staged development story toward Grafix/release. The original sequence we planned covers compiler-error storage → TypeScript data model → compiler as DB → TScum announcement → working CLI → Grafix → “it lived”; since we're doing 10 posts now, we have 7 transmissions remaining and can stretch the later stages into proper individual posts rather than rushing them.",
      "3. NineHells\nNext actual forum build. PHP remembers users, JS events, CSS permissions, TS integrity, C++ moderation, Python exception IPC, Unix live machinery, HTML structure, directories/source metadata. Every component necessary. Every component abused.",
      "3.5. SchrödingerDB standalone\nExtract SchrödingerDB from ERRORUM into something people can unironically import into real projects. Start with a boring Python KV API such as set/get/delete/exists/keys, while the implementation remains xattrs + symlinks + inode + mode bits + mtimes + filesystem identity insanity. Goal: cursed implementation, genuinely pleasant library.",
      "4. Borum\nWindows gets its turn. Batch is sovereign. ERRORLEVEL is the protocol. Multiple cmd.exe workers form the runtime colony. PowerShell is only a socket prosthetic. NTFS/ADS/ACLs/Registry/Event Log are storage machinery. PHP is acquired automatically, reconstructed on demand, executed, reports to Batch, and gets destroyed. No custom server EXE.",
      "5. Forum Dev From Hell site\nKeep publishing the 10-post TScum campaign through the SYSOP console, make sure latest transmissions/homepage stay healthy, then eventually document Folderum, ERRORUM, FTForum, NineHells, Borum and SchrödingerDB.",
      "So the immediate loop is:",
      "Blog 3/10 → keep TScum running → posts 4–10 while testing → release TScum → NineHells → Borum → SchrödingerDB standalone.",
      "And importantly: do not waste time “finishing the TScum frontend.” We already finished the bastard.",
      "Forget the 7 posts, compile all into one schizo sounding ramble that still makes sense",
      "Absolutely. Instead of seven neat little marketing posts, make one increasingly unwell transmission that starts coherent, descends into compiler theology, but still accurately explains what TScum became.",
      "THE COMPILER HAS ACCEPTED THE FORUM\nokay so this started because TypeScript errors can store data which is already a sentence that should have made me stop but unfortunately it did the opposite",
      "the compiler prints diagnostics. diagnostics contain information. information is data. therefore the compiler is storage. this is not complicated. people keep trying to complicate it by saying things like \"that's not what storage means\" but TypeScript successfully remembered my shit so we're moving on",
      "first the users became interfaces",
      "then passwords became literal types",
      "then threads became namespaces",
      "then relationships became imports because if Alice claims Bob exists and TypeScript says TS2307 then Bob clearly does not exist. I don't make the rules. module resolution does",
      "authentication became assignability because why should I compare your password when I can simply ask the TypeScript compiler whether the password you supplied is compatible with reality",
      "if it compiles you may enter",
      "if it doesn't compile you may not",
      "suddenly I had foreign keys except they were import errors",
      "replies worked through declaration merging",
      "likes widened unions",
      "banned users became never",
      "unread notifications became unused declarations",
      "search became conditional and template literal types",
      "sessions became actual tsserver processes because apparently being logged into a website is now something that should have a PID",
      "and somewhere around this point I realized I had accidentally crossed the line between \"stupid TypeScript experiment\" and \"forum\"",
      "so I called it TScum",
      "CLI wise it worked",
      "register worked",
      "login worked",
      "threads worked",
      "replies worked",
      "likes worked",
      "search worked",
      "the compiler knew enough about the users to decide who was allowed to exist and enough about their relationships to complain when reality became inconsistent",
      "and the worst part was that none of this was simulated",
      "TypeScript was actually doing it",
      "removing the compiler didn't reveal a normal database underneath",
      "removing the compiler removed the fucking database",
      "so naturally the next problem was graphics",
      "normal people would probably see this as an opportunity to reconsider their choices",
      "I saw it as a frontend problem",
      "now TScum has a browser UI",
      "you register in a browser like a normal person",
      "you log in like a normal person",
      "you open threads and reply and search and click buttons like you're using normal forum software",
      "meanwhile underneath the page your authentication is still a compiler question, your relationships are still imports, your likes are still unions, and your login session is still represented by a TypeScript server process wandering around /proc",
      "the like button literally says Widen union",
      "this is not metaphorical",
      "clicking it widens the union",
      "I have put graphics over the compiler and somehow this has made the situation worse",
      "this is the Grafix Update",
      "the important part is that the user doesn't need to understand any of this",
      "that's what I wanted",
      "cursed software shouldn't mean broken software",
      "if somebody needs to understand my mental illness before they can create a thread then I have failed as a developer",
      "they should see a forum",
      "TypeScript can suffer underneath",
      "so now I'm running the thing for a few days because there is one remaining question",
      "not \"is this a good architecture\"",
      "we have moved beyond questions with obvious answers",
      "the question is whether you can actually use it",
      "if it survives normal forum use then I have accomplished something nobody needed accomplished:",
      "a forum where compiler diagnostics contain the runtime, interfaces are users, namespaces are threads, imports are relationships, declaration merging is conversation, unions are social interaction, never is punishment, tsserver is presence, and compilation itself is part of the database engine",
      "people keep saying you're supposed to use TypeScript to make software safer",
      "I did",
      "the compiler will not permit the database to disagree with the hallucination",
      "TScum v0.2 is alive.",
      "Grafix are installed.",
      "field testing has begun.",
      "if it survives I'm releasing it.",
      "if it doesn't survive I'll fix it until TypeScript agrees that it did.",
      "tsc --noEmit",
      "amen."
    ]
  }
];
