#!/usr/bin/env bash
set -Eeuo pipefail

SITE_DIR="${1:-/var/www/blogging}"
cd "$SITE_DIR"

for f in admin.html admin.js admin-config.js blog-data.js; do
  [[ -f "$f" ]] || { echo "Missing $SITE_DIR/$f" >&2; exit 1; }
done

command -v node >/dev/null 2>&1 || {
  echo "Node.js is required. On Debian/Ubuntu: sudo apt install -y nodejs" >&2
  exit 1
}

echo "This configures the no-Cloudflare SYSOP console."
echo "The GitHub token will be AES-256-GCM encrypted with your SYSOP password."
echo "Only the encrypted blob is written to admin-secret.js."
echo
read -rsp "Fine-grained GitHub token: " GH_TOKEN; echo
read -rsp "SYSOP password: " ADMIN_PASSWORD; echo
read -rsp "SYSOP password again: " ADMIN_PASSWORD_2; echo
[[ -n "$GH_TOKEN" ]] || { echo "Token cannot be empty." >&2; exit 1; }
[[ "$ADMIN_PASSWORD" == "$ADMIN_PASSWORD_2" ]] || { echo "Passwords do not match." >&2; exit 1; }

GH_TOKEN="$GH_TOKEN" ADMIN_PASSWORD="$ADMIN_PASSWORD" node <<'NODE'
const fs = require('node:fs');
const crypto = require('node:crypto');
const token = process.env.GH_TOKEN;
const password = process.env.ADMIN_PASSWORD;
const iterations = 600000;
const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const key = crypto.pbkdf2Sync(password, salt, iterations, 32, 'sha256');
const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
const encrypted = Buffer.concat([cipher.update(token, 'utf8'), cipher.final()]);
const tag = cipher.getAuthTag();
const ciphertext = Buffer.concat([encrypted, tag]);
const out = `// Generated by configure-admin.sh. Public encrypted token blob.\nwindow.FDH_ADMIN_SECRET = ${JSON.stringify({
  v: 1,
  kdf: 'PBKDF2-SHA256',
  cipher: 'AES-256-GCM',
  iterations,
  salt: salt.toString('base64'),
  iv: iv.toString('base64'),
  ciphertext: ciphertext.toString('base64')
}, null, 2)};\n`;
fs.writeFileSync('admin-secret.js', out, {mode: 0o644});
NODE

unset GH_TOKEN ADMIN_PASSWORD ADMIN_PASSWORD_2

echo
echo "Wrote $SITE_DIR/admin-secret.js"
echo "IMPORTANT: this is encrypted, not magically secret."
echo "Anyone can download the blob and attempt offline password guesses."
echo "Use a strong password and a token restricted ONLY to this repo with Contents read/write."
echo

if [[ -d .git ]]; then
  git add admin-secret.js admin-config.js admin.html admin.js README.md SETUP-POST-CONSOLE.md configure-admin.sh 2>/dev/null || true
  if ! git diff --cached --quiet; then
    git commit -m "Configure direct SYSOP publisher"
    echo "Committed changes. Run: git push"
  else
    echo "Nothing new to commit."
  fi
else
  echo "No .git directory found here. Commit admin-secret.js and the rebuilt site to your repo manually."
fi
